### ISSUE TITLE
Sidan blir för smal på iPad

### ISSUE THREAD

**Issue by magicus** [staffanm/lagen.nu#35]
## Vilken sida har ett fel/problem? Ange länk (URL) eller beskriv hur du kommit till sidan.

http://ferenda.lagen.nu/1998:1276 (antagligen på fler ställen...)
## Beskriv felet, gärna exakt vad som är fel och hur det borde vara istället?

Det är svårläst pga för mycket marginal. Inforutorna till höger borde ligga ända ut i kanten.
## Är det fel i själva informationen, eller visas informationen på fel sätt?

Fel i visningen. Jfr två screenshots gamla och nya sajten.

![image](https://cloud.githubusercontent.com/assets/6209108/19272728/ea84aa72-8fc9-11e6-9618-02fbc4416418.png)
![image](https://cloud.githubusercontent.com/assets/6209108/19272729/eab14a32-8fc9-11e6-8eb0-46a6a4a7463a.png)

**Comment by staffanm** [comment]
Nuvarande CSS ser lite bättre ut på ipad (med skärmvidd == 768px), men egentligen borde vänsternavigationen vara dold per default -- det blir för trångt med tre kolumner, särskilt som vänsternavigationen av någon anledning inte fixeras till övre vänstra hörnet på ipad, utan försvinner när man börjar scrolla.

Återöppnar denna tills jag kan få till en bättre CSS-lösning. Tänker att en vanlig ipad är bred nog för att ha lagtext + kommentarer sida vid sida i porträttläge, och i landskapsläge får vänsternavigationen också plats.

**Comment by staffanm** [comment]
Nu finns en hyfsad funktion för vänsternavigationen för skärmstorlekar som ipad och och mindre.
